#!/sbin/busybox sh

if [ "a$2" != "a" ];then

filename=$(basename $2)

if [ "a$3" == "a" ];then
  evalcmd='eval "echo \$$filename"'
  eval $evalcmd
else
  evalcmd='eval "$filename=$3"'
  eval $evalcmd
  evalcmd='eval "echo \$$filename"'
  eval $evalcmd

echo "$speaker_volume $speaker_volume" > /sys/class/misc/boeffla_sound/speaker_volume;
echo "$headphone_volume $headphone_volume" > /sys/class/misc/boeffla_sound/headphone_volume;

if [ "$eq_selection" == "0" ];
then
case "$eq_preset" in
  0)
	echo 0 > /sys/class/misc/boeffla_sound/eq;
    ;;
  1)
	echo "12 8 3 -1 1" > /sys/class/misc/boeffla_sound/eq_gains;
	echo "1 4027 1031 0 276" > /sys/class/misc/boeffla_sound/eq_bands;
	echo "2 8076 61555 456 456" > /sys/class/misc/boeffla_sound/eq_bands;
	echo "3 7256 62323 2644 1368" > /sys/class/misc/boeffla_sound/eq_bands;
	echo "4 5774 63529 1965 4355" > /sys/class/misc/boeffla_sound/eq_bands;
	echo "5 1380 1369 0 16384" > /sys/class/misc/boeffla_sound/eq_bands;
    ;;
  2)
	echo "10 7 0 2 5" > /sys/class/misc/boeffla_sound/eq_gains;
	echo "1 4027 1031 0 276" > /sys/class/misc/boeffla_sound/eq_bands;
	echo "2 8076 61555 456 456" > /sys/class/misc/boeffla_sound/eq_bands;
	echo "3 7256 62323 2644 1368" > /sys/class/misc/boeffla_sound/eq_bands;
	echo "4 5774 63529 1965 4355" > /sys/class/misc/boeffla_sound/eq_bands;
	echo "5 1380 1369 0 16384" > /sys/class/misc/boeffla_sound/eq_bands;
    ;;
  3)
	echo "-5 1 0 4 3" > /sys/class/misc/boeffla_sound/eq_gains;
	echo "1 4027 1031 0 276" > /sys/class/misc/boeffla_sound/eq_bands;
	echo "2 8076 61555 456 456" > /sys/class/misc/boeffla_sound/eq_bands;
	echo "3 7256 62323 2644 1368" > /sys/class/misc/boeffla_sound/eq_bands;
	echo "4 5774 63529 1965 4355" > /sys/class/misc/boeffla_sound/eq_bands;
	echo "5 1380 1369 0 16384" > /sys/class/misc/boeffla_sound/eq_bands;
    ;;
  4)
	echo "0 0 0 -3 -5" > /sys/class/misc/boeffla_sound/eq_gains;
	echo "1 4027 1031 0 276" > /sys/class/misc/boeffla_sound/eq_bands;
	echo "2 8076 61555 456 456" > /sys/class/misc/boeffla_sound/eq_bands;
	echo "3 7256 62323 2644 1368" > /sys/class/misc/boeffla_sound/eq_bands;
	echo "4 5774 63529 1965 4355" > /sys/class/misc/boeffla_sound/eq_bands;
	echo "5 1380 1369 0 16384" > /sys/class/misc/boeffla_sound/eq_bands;
    ;;
  5)
	echo "4 3 2 2 3" > /sys/class/misc/boeffla_sound/eq_gains;
	echo "1 4027 1031 0 276" > /sys/class/misc/boeffla_sound/eq_bands;
	echo "2 8076 61555 456 456" > /sys/class/misc/boeffla_sound/eq_bands;
	echo "3 7256 62323 2644 1368" > /sys/class/misc/boeffla_sound/eq_bands;
	echo "4 5774 63529 1965 4355" > /sys/class/misc/boeffla_sound/eq_bands;
	echo "5 1380 1369 0 16384" > /sys/class/misc/boeffla_sound/eq_bands;
    ;;
  6)
	echo "12 8 4 2 3" > /sys/class/misc/boeffla_sound/eq_gains;
	echo "1 4027 1031 0 276" > /sys/class/misc/boeffla_sound/eq_bands;
	echo "2 8076 61555 456 456" > /sys/class/misc/boeffla_sound/eq_bands;
	echo "3 7256 62323 2644 1368" > /sys/class/misc/boeffla_sound/eq_bands;
	echo "4 5774 63529 1965 4355" > /sys/class/misc/boeffla_sound/eq_bands;
	echo "5 1380 1369 0 16384" > /sys/class/misc/boeffla_sound/eq_bands;
    ;;
esac;
else
    echo "1 $eq_band1" > /sys/class/misc/boeffla_sound/eq_gains_alt;
    echo "2 $eq_band2" > /sys/class/misc/boeffla_sound/eq_gains_alt;
    echo "3 $eq_band3" > /sys/class/misc/boeffla_sound/eq_gains_alt;
    echo "4 $eq_band4" > /sys/class/misc/boeffla_sound/eq_gains_alt;
    echo "5 $eq_band5" > /sys/class/misc/boeffla_sound/eq_gains_alt;
fi

fi
fi

