#!/sbin/busybox sh
cd /

busybox mount -t proc proc /proc
busybox mount -t sysfs sysfs /sys

if busybox grep -q 1 /sys/class/power_supply/battery/batt_lp_charging ; then
  # low power mode
  echo 0 > /proc/sys/kernel/rom_feature_set
  cp -a /res/misc/init.41/* /
  chmod 755 /innt
  chmod 644 /*.rc
  chmod 644 /*.prop
  exec /sbin/init2
fi

SECONDROM=1
NOBOOTLOGO=0
mkdir -p /dev/block
mkdir /dev/input
mkdir /dev/graphics
mknod /dev/graphics/fb0 c 29 0
mknod /dev/input/event1 c 13 65
mknod /dev/input/event2 c 13 66
mknod /dev/input/event8 c 13 72
mknod /dev/input/event9 c 13 73
mknod /dev/ashmem c 10 60
mknod /dev/block/mmcblk0p9 b 179 9
mknod /dev/block/mmcblk0p12 b 179 12
mknod /dev/block/loop0 b 7 0

mkdir /mnt
chmod 755 /mnt
mkdir /.secondrom
mount -t ext4 /dev/block/mmcblk0p12 /.secondrom

NEXTBOOT=`cat /.secondrom/media/.nextboot`
rm -f /.secondrom/media/.nextboot
DEFAULTROM=`cat /.secondrom/media/.defaultrom`

if grep -q bootmode=2 /proc/cmdline ; then
  NEXTBOOT=0
fi

#move .secondrom folder back to the original location if cm10.1 moved it to a subfolder
if [ -d /.secondrom/media/0/.secondrom ];then
  if [ ! -d /.secondrom/media/.secondrom ];then
    mkdir /.secondrom/media/.secondrom
    mv -f /.secondrom/media/0/.secondrom/* /.secondrom/media/.secondrom
    rmdir /.secondrom/media/0/.secondrom
  fi
fi

if [ "$NEXTBOOT" == "0" ]; then
  mv -f /res/etc /
  umount /.secondrom
  echo 0 > /proc/sys/kernel/rom_feature_set
  mv -f /res/misc/init.41/* /
  mv -f /res/misc/recovery/* /
  chmod 755 /innt
  chmod 644 /*.smdk4x12
  chmod 644 /*.rc
  chmod 644 /*.prop
  chmod -R 755 /lib
  exec /sbin/init2
fi

SECONDROM=1
NOBOOTLOGO=0
[ -f /.secondrom/media/.secondrom/system.img ] || SECONDROM=0
[ -f /.secondrom/media/.nobootlogo ] && NOBOOTLOGO=1

if [ "$SECONDROM" == "0" ];then
  if [ "$NOBOOTLOGO" == "0" ];then
    /sbin/choose_rom $SECONDROM
  fi
else
  if [ ! -f /.secondrom/media/.secondrom/data/.layout_version ];then
    echo 2 > /.secondrom/media/.secondrom/data/.layout_version
    mkdir /.secondrom/media/0
  fi
  if [ "$NEXTBOOT" == "1" ];then
    SECONDROM=0;
  elif [ "$NEXTBOOT" == "2" ];then
    SECONDROM=1;
  else
    if [ "$NOBOOTLOGO" == "1" ];then
      SECONDROM=$DEFAULTROM
    elif [ "$DEFAULTROM" == "1" ];then
      /sbin/choose_rom $SECONDROM
      if [ "$?" == "1" ]; then
        SECONDROM=0
      else
        SECONDROM=1
      fi
    else
      /sbin/choose_rom $SECONDROM
      if [ "$?" == "1" ]; then
        SECONDROM=1
      else
        SECONDROM=0
      fi
    fi
  fi
fi

if [ "$SECONDROM" == "1" ]; then
  mount -t ext4 /.secondrom/media/.secondrom/system.img /system
else
  mount -t ext4 /dev/block/mmcblk0p9 /system
fi


MIUI=0
CM10=0
CM101=0
SAMMY42=0

[ -f /system/framework/miui-framework.jar ] && MIUI=1
[ -f /system/framework/seccamera.jar ] || CM10=1
[ -f /system/framework/framework2.jar ] || CM101=1
[ -f /system/framework/telephony-common.jar ] && SAMMY42=1

if [ "$CM101" == 1 ];
then
  echo 7 > /proc/sys/kernel/rom_feature_set
#  mv -f /lib/modules/dhd_cm.ko /lib/modules/dhd.ko
  mv -f /res/misc/init.cm10.1/* /
else
  if [ "$CM10" == 1 ];
  then
    echo 3 > /proc/sys/kernel/rom_feature_set
    mv -f /lib/modules/dhd_cm.ko /lib/modules/dhd.ko
    mv -f /res/misc/init.cm10/* /
  else
    if [ "$SAMMY42" == 1 ];
    then
      echo 6 > /proc/sys/kernel/rom_feature_set
      mv -f /res/misc/init.42/* /
    else
      echo 2 > /proc/sys/kernel/rom_feature_set
      mv -f /res/misc/init.41/* /
    fi
  fi
fi

if [ "$SECONDROM" == "1" ];then
  mv /init.smdk4x12.rc.2 /init.smdk4x12.rc
  mv /init.rc.2 /init.rc
  mv /fstab.smdk4x12.2 /fstab.smdk4x12
else
  rm -f /init.rc.2 /init.smdk4x12.rc.2 /fstab.smdk4x12.2
fi

umount -f /system
umount -f /.secondrom
	
rm -rf /res/misc/init*
chmod 755 /innt
chmod 644 /*.smdk4x12
chmod 644 /*.rc
chmod 644 /*.prop
chmod -R 755 /lib

# only if asked by user via stweaks
if [ -e /system/run_fix_media ]; then
# data mount
$BB mount -t ext4 /dev/block/mmcblk0p12 /data;

$BB rm /system/run_fix_media;

if [ -e /data/media/Android/data/ ]; then
$BB rm -rf /data/media/Android/data/com.cooliris.media;
$BB rm -rf /data/media/Android/data/com.android.gallery3d;
$BB rm -rf /data/media/Android/data/com.google.android.gallery3d;
$BB rm -rf /data/media/Android/data/com.android.providers.media;
$BB rm -rf /data/media/Android/data/com.google.android.music;
$BB rm -rf /data/data/com.android.providers.media/databases/*;
fi;

# data unmount
sync;
$BB umount -l /data;
fi;

# only if asked by user via stweaks
if [ -e /system/run_fix_yournaling ]; then
# CACHE partition
$BB umount -f /cache;
if [ -e /system/run_fix_partitions ]; then
/sbin/e2fsck1 -yf /dev/block/mmcblk0p8;
fi;
/sbin/tune2fs -c -1 -i 0 -o journal_data_writeback -O ^has_journal /dev/block/mmcblk0p8;
#$BB mount -o rw,noatime,data=writeback /dev/block/mmcblk0p8 /cache;
# SYSTEM partition
$BB umount -f /system;
sleep 1;
if [ -e /system/run_fix_partitions ]; then
/sbin/e2fsck1 -yf /dev/block/mmcblk0p9;
fi;
/sbin/tune2fs -c -1 -i 0 -o journal_data_writeback -O ^has_journal /dev/block/mmcblk0p9;
#$BB mount -o remount,rw,noatime /system /system;
# DATA partition
$BB umount -f /data;
sleep 1;
if [ -e /system/run_fix_partitions ]; then
/sbin/e2fsck1 -yf /dev/block/mmcblk0p12;
fi;
/sbin/tune2fs -c -1 -i 0 -o journal_data_writeback -O ^has_journal /dev/block/mmcblk0p12;
#$BB mount -o remount,rw,noatime /data /data;
fi;
$BB rm /system/run_fix_partitions;
$BB rm /system/run_fix_yournaling;
$BB umount -f /system;

exec /sbin/init2

