#!/sbin/busybox sh
cd /;

BB=/sbin/busybox

$BB mount -t proc proc /proc;
$BB mount -t sysfs sysfs /sys;

if $BB grep -q 1 /sys/class/power_supply/battery/batt_lp_charging ; then
  # low power mode
  echo 0 > /proc/sys/kernel/rom_feature_set;
  $BB cp -a /res/misc/init.41/* /
  $BB chmod 755 /innt
  $BB chmod 644 /*.rc
  $BB chmod 644 /*.prop
  exec /sbin/init2;
fi;

SECONDROM=1
NOBOOTLOGO=0
mkdir -p /dev/block
mkdir /dev/input
mkdir /dev/graphics
mknod /dev/graphics/fb0 c 29 0
mknod /dev/input/event1 c 13 65
mknod /dev/input/event2 c 13 66
mknod /dev/input/event8 c 13 72
mknod /dev/input/event9 c 13 73
mknod /dev/ashmem c 10 60
mknod /dev/block/mmcblk0p9 b 179 9
mknod /dev/block/mmcblk0p12 b 179 12
mknod /dev/block/loop0 b 7 0

mkdir /mnt;
$BB chmod 755 /mnt;
mkdir /.secondrom;
$BB mount -t ext4 /dev/block/mmcblk0p12 /.secondrom;

NEXTBOOT=`cat /.secondrom/media/.nextboot`
$BB rm -f /.secondrom/media/.nextboot
DEFAULTROM=`cat /.secondrom/media/.defaultrom`

if grep -q bootmode=2 /proc/cmdline ; then
  NEXTBOOT=0
fi

#move .secondrom folder back to the original location if cm10.1 moved it to a subfolder
if [ -d /.secondrom/media/0/.secondrom ];then
  if [ ! -d /.secondrom/media/.secondrom ];then
    $BB mkdir /.secondrom/media/.secondrom
    $BB mv -f /.secondrom/media/0/.secondrom/* /.secondrom/media/.secondrom
    $BB rmdir /.secondrom/media/0/.secondrom
  fi
fi

if [ "$NEXTBOOT" == "0" ]; then
 $BB mv -f /res/etc /
  $BB umount /.secondrom;
  echo 0 > /proc/sys/kernel/rom_feature_set;
  $BB mv -f /res/misc/init.41/* /
  $BB mv -f /res/misc/recovery/* /
  $BB chmod 755 /innt;
  $BB chmod 644 /*.smdk4x12;
  $BB chmod 644 /*.rc;
  $BB chmod 644 /*.prop;
  $BB chmod -R 755 /lib;
  exec /sbin/init2
fi;

SECONDROM=1
NOBOOTLOGO=0
[ -f /.secondrom/media/.secondrom/system.img ] || SECONDROM=0
[ -f /.secondrom/media/.nobootlogo ] && NOBOOTLOGO=1

if [ "$SECONDROM" == "0" ];then
  if [ "$NOBOOTLOGO" == "0" ];then
    /sbin/choose_rom $SECONDROM
  fi
else
  if [ ! -f /.secondrom/media/.secondrom/data/.layout_version ];then
    echo 2 > /.secondrom/media/.secondrom/data/.layout_version
    mkdir /.secondrom/media/0
  fi
  if [ "$NEXTBOOT" == "1" ];then
    SECONDROM=0;
  elif [ "$NEXTBOOT" == "2" ];then
    SECONDROM=1;
  else
    if [ "$NOBOOTLOGO" == "1" ];then
      SECONDROM=$DEFAULTROM
    elif [ "$DEFAULTROM" == "1" ];then
      /sbin/choose_rom $SECONDROM
      if [ "$?" == "1" ]; then
        SECONDROM=0
      else
        SECONDROM=1
      fi
    else
      /sbin/choose_rom $SECONDROM
      if [ "$?" == "1" ]; then
        SECONDROM=1
      else
        SECONDROM=0
      fi
    fi
  fi
fi

if [ "$SECONDROM" == "1" ]; then
  $BB mount -t ext4 /.secondrom/media/.secondrom/system.img /system;
else
  $BB mount -t ext4 /dev/block/mmcblk0p9 /system;
fi;

# linking /system/bin to /bin for crond
ln -s /system/bin/ /bin;

MIUI=0
CM10=0
CM101=0

[ -f /system/framework/miui-framework.jar ] && MIUI=1
[ -f /system/framework/seccamera.jar ] || CM10=1
[ -f /system/framework/framework2.jar ] || CM101=1

if [ "$CM101" == 1 ];
then
echo 3 > /proc/sys/kernel/rom_feature_set;
  $BB mv -f /lib/modules/dhd_cm.ko /lib/modules/dhd.ko;
  $BB mv -f /res/misc/init.cm10.1/* /;
else
if [ "$CM10" == 1 ];
  then
echo 3 > /proc/sys/kernel/rom_feature_set;
    $BB mv -f /lib/modules/dhd_cm.ko /lib/modules/dhd.ko;
    $BB mv -f /res/misc/init.cm10/* /;
  else
echo 2 > /proc/sys/kernel/rom_feature_set;
    $BB mv -f /res/misc/init.41/* /
    $BB rm -f /lib/modules/dhd_cm.ko
  fi
fi

if [ "$SECONDROM" == "1" ];then
  $BB mv /init.smdk4x12.rc.2 /init.smdk4x12.rc
  $BB mv /init.rc.2 /init.rc
  $BB mv /fstab.smdk4x12.2 /fstab.smdk4x12
else
  $BB rm -f /init.rc.2 /init.smdk4x12.rc.2 /fstab.smdk4x12.2
fi

#$BB umount -f /system;
$BB umount -f /.secondrom;
	
$BB rm -rf /res/misc/init*;
$BB chmod 755 /innt;
$BB chmod 644 /*.smdk4x12;
$BB chmod 644 /*.rc;
$BB chmod 644 /*.prop;
$BB chmod -R 755 /lib;

# only if asked by user via stweaks
if [ -e /system/run_fix_media ]; then
# data mount
$BB mount -t ext4 /dev/block/mmcblk0p12 /data;

$BB rm /system/run_fix_media;

if [ -e /data/media/Android/data/ ]; then
$BB rm -rf /data/media/Android/data/com.cooliris.media;
$BB rm -rf /data/media/Android/data/com.android.gallery3d;
$BB rm -rf /data/media/Android/data/com.google.android.gallery3d;
$BB rm -rf /data/media/Android/data/com.android.providers.media;
$BB rm -rf /data/media/Android/data/com.google.android.music;
$BB rm -rf /data/data/com.android.providers.media/databases/*;
fi;

# data unmount
sync;
$BB umount -l /data;
fi;

# only if asked by user via stweaks
if [ -e /system/run_fix_yournaling ]; then
# CACHE partition
$BB umount -f /cache;
if [ -e /system/run_fix_partitions ]; then
/sbin/e2fsck1 -yf /dev/block/mmcblk0p8;
fi;
/sbin/tune2fs -c -1 -i 0 -o journal_data_writeback -O ^has_journal /dev/block/mmcblk0p8;
#$BB mount -o rw,noatime,data=writeback /dev/block/mmcblk0p8 /cache;
# SYSTEM partition
$BB umount -f /system;
sleep 1;
if [ -e /system/run_fix_partitions ]; then
/sbin/e2fsck1 -yf /dev/block/mmcblk0p9;
fi;
/sbin/tune2fs -c -1 -i 0 -o journal_data_writeback -O ^has_journal /dev/block/mmcblk0p9;
#$BB mount -o remount,rw,noatime /system /system;
# DATA partition
$BB umount -f /data;
sleep 1;
if [ -e /system/run_fix_partitions ]; then
/sbin/e2fsck1 -yf /dev/block/mmcblk0p12;
fi;
/sbin/tune2fs -c -1 -i 0 -o journal_data_writeback -O ^has_journal /dev/block/mmcblk0p12;
#$BB mount -o remount,rw,noatime /data /data;
fi;
$BB rm /system/run_fix_partitions;
$BB rm /system/run_fix_yournaling;
$BB umount -f /system;
exec /sbin/init2

