#!/sbin/busybox sh

mount -o remount,rw /;
mount -o remount,rw /system;

TMPFILE=$(mktemp -t);
TMPFILE2=$(mktemp -t);
OLD_VERSION=`cat /proc/version | sed 's/.*-V//g' | sed 's/-S.*//g'`;

TESTCONNECTION=`wget http://www.google.com -O $TMPFILE > /dev/null 2>&1`;
if [ $? != 0 ]; then
	echo "Problem: no internet connection! connect and try again";
else
	wget http://68.233.243.9/megosztasok/SGSIII/ -O $TMPFILE > /dev/null 2>&1;
	cat $TMPFILE | grep ".*-V" |  sed 's/.*-V//g' | sed 's/-S.*//g' | sed 's/[-\[].*//g' > $TMPFILE2;

	for version in $(cat $TMPFILE2); do 
		# debug
		#echo $version " - " $OLD_VERSION;

		expr $version \> $OLD_VERSION >/dev/null && echo "There is a new version of this kernel available!!!"; 
		expr "1.3.5" \= $version >/dev/null && break;
	done;
	
fi;

rm $TMPFILE;
rm $TMPFILE2;
